version: '3'

services:
  rest:
    build:
      context: ./api/rest
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      
  graphql:
    build:
      context: ./api/graphql
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  grpc:
    build:
      context: ./api/grpc
      dockerfile: Dockerfile
    ports:
      - "50051:50051"

  
